include:
  - project: 'devops/devops-tools'
    ref: master
    file: '/templates/.gitlab-ci-template.yml'

variables:
  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
  CI_IS_DEPLOY_OLD: "true"
  DS_PYTHON_VERSION: 3


#testing4
